var profile_data = {
    "1": {
        "name": "gender"
        , "text": "Your gender"
        , "content": {
            "male": "Male"
            , "female": "Female"
        }
    }
    , "2": {
        "name": "age"
        , "text": "Your age range"
        , "content": {
            "16-": "under 16 "
            , "16-20": "16-20"
            , "21-25": "21-25"
            , "26-30": "26-30"
            , "31-35": "31-35"
            , "36-40": "36-40"
            , "41-45": "41-45"
            , "46-50": "46-50"
            , "51-55": "51-55"
            , "56-60": "56-60"
            , "60+": "over 60"
        }
    }
    , "3": {
        "name": "country"
        , "text": "Your country"
        , "content": {
            "bangladesh": "Bangladesh"
            , "bosnia-herzegovina": "Bosnia-herzegovina"
            , "brazil": "Brazil"
            , "bulgaria": "Bulgaria"
            , "croatia": "Croatia"
            , "egypt": "Egypt"
            , "germany": "Germany"
            , "greece": "Greece"
            , "italy": "Italy"
            , "india": "India"
            , "indonesia": "Indonesia"
            , "malaysia": "Malaysia"
            , "nigeria": "Nigeria"
            , "romania": "Romania"
            , "russia": "Russia"
            , "serbia": "Serbia"
            , "slovakia": "Slovakia"
            , "spain": "Spain"
            , "turkey": "Turkey"
            , "philippines": "Philippines"
            , "poland": "Poland"
            , "portugal": "Portugal"
            , "ukraine": "Ukraine"
            , "united states": "United states"
            , "venezuela": "Venezuela"
            //
            //
            // "Afghanistan": "Afghanistan"
            // , "Albania": "Albania"
            // , "Algeria": "Algeria"
            // , "American Samoa": "American Samoa"
            // , "Andorra": "Andorra"
            // , "Angola": "Angola"
            // , "Anguilla": "Anguilla"
            // , "Antigua and Barbuda": "Antigua and Barbuda"
            // , "Argentina": "Argentina"
            // , "Armenia": "Armenia"
            // , "Aruba": "Aruba"
            // , "Australia": "Australia"
            // , "Austria": "Austria"
            // , "Azerbaijan": "Azerbaijan"
            // , "Bahamas": "Bahamas"
            // , "Bahrain": "Bahrain"
            // , "Bangladesh": "Bangladesh"
            // , "Barbados": "Barbados"
            // , "Belarus": "Belarus"
            // , "Belgium": "Belgium"
            // , "Belize": "Belize"
            // , "Benin": "Benin"
            // , "Bermuda": "Bermuda"
            // , "Bhutan": "Bhutan"
            // , "Bolivia": "Bolivia"
            // , "Bonaire": "Bonaire"
            // , "Bosnia-Herzegovina": "Bosnia-Herzegovina"
            // , "Botswana": "Botswana"
            // , "Bouvet Island": "Bouvet Island"
            // , "Brazil": "Brazil"
            // , "Brunei": "Brunei"
            // , "Bulgaria": "Bulgaria"
            // , "Burkina Faso": "Burkina Faso"
            // , "Burundi": "Burundi"
            // , "Cambodia": "Cambodia"
            // , "Cameroon": "Cameroon"
            // , "Canada": "Canada"
            // , "Cape Verde": "Cape Verde"
            // , "Cayman Islands": "Cayman Islands"
            // , "Central African Republic": "Central African Republic"
            // , "Chad": "Chad"
            // , "Chile": "Chile"
            // , "China": "China"
            // , "Christmas Island": "Christmas Island"
            // , "Cocos (Keeling) Islands": "Cocos (Keeling) Islands"
            // , "Colombia": "Colombia"
            // , "Comoros": "Comoros"
            // , "Congo  Democratic Republic of the (Zaire) ": "Congo  Democratic Republic of the (Zaire)"
            // , "Congo  Republic of": "Congo  Republic of"
            // , "Cook Islands": "Cook Islands"
            // , "Costa Rica": "Costa Rica"
            // , "Croatia": "Croatia"
            // , "Cuba": "Cuba"
            // , "Curacao": "Curacao"
            // , "Cyprus": "Cyprus"
            // , "Czech Republic": "Czech Republic"
            // , "Denmark": "Denmark"
            // , "Djibouti": "Djibouti"
            // , "Dominica": "Dominica"
            // , "Dominican Republic": "Dominican Republic"
            // , "Ecuador": "Ecuador"
            // , "Egypt": "Egypt"
            // , "El Salvador": "El Salvador"
            // , "Equatorial Guinea": "Equatorial Guinea"
            // , "Eritrea": "Eritrea"
            // , "Estonia": "Estonia"
            // , "Ethiopia": "Ethiopia"
            // , "Falkland Islands": "Falkland Islands"
            // , "Faroe Islands": "Faroe Islands"
            // , "Fiji": "Fiji"
            // , "Finland": "Finland"
            // , "France": "France"
            // , "French Guiana": "French Guiana"
            // , "Gabon": "Gabon"
            // , "Gambia": "Gambia"
            // , "Georgia": "Georgia"
            // , "Germany": "Germany"
            // , "Ghana": "Ghana"
            // , "Gibraltar": "Gibraltar"
            // , "Greece": "Greece"
            // , "Greenland": "Greenland"
            // , "Grenada": "Grenada"
            // , "Guadeloupe (French)": "Guadeloupe (French)"
            // , "Guam (USA)": "Guam (USA)"
            // , "Guatemala": "Guatemala"
            // , "Guinea": "Guinea"
            // , "Guinea Bissau": "Guinea Bissau"
            // , "Guyana": "Guyana"
            // , "Haiti": "Haiti"
            // , "Holy See": "Holy See"
            // , "Honduras": "Honduras"
            // , "Hong Kong": "Hong Kong"
            // , "Hungary": "Hungary"
            // , "Iceland": "Iceland"
            // , "India": "India"
            // , "Indonesia": "Indonesia"
            // , "Iran": "Iran"
            // , "Iraq": "Iraq"
            // , "Ireland": "Ireland"
            // , "Israel": "Israel"
            // , "Italy": "Italy"
            // , "Ivory Coast (Cote D`Ivoire)": "Ivory Coast (Cote D`Ivoire)"
            // , "Jamaica": "Jamaica"
            // , "Japan": "Japan"
            // , "Jordan": "Jordan"
            // , "Kazakhstan": "Kazakhstan"
            // , "Kenya": "Kenya"
            // , "Kiribati": "Kiribati"
            // , "Kosovo": "Kosovo"
            // , "Kuwait": "Kuwait"
            // , "Kyrgyzstan": "Kyrgyzstan"
            // , "Laos": "Laos"
            // , "Latvia": "Latvia"
            // , "Lebanon": "Lebanon"
            // , "Lesotho": "Lesotho"
            // , "Liberia": "Liberia"
            // , "Libya": "Libya"
            // , "Liechtenstein": "Liechtenstein"
            // , "Lithuania": "Lithuania"
            // , "Luxembourg": "Luxembourg"
            // , "Macau": "Macau"
            // , "Macedonia": "Macedonia"
            // , "Madagascar": "Madagascar"
            // , "Malawi": "Malawi"
            // , "Malaysia": "Malaysia"
            // , "Maldives": "Maldives"
            // , "Mali": "Mali"
            // , "Malta": "Malta"
            // , "Marshall Islands": "Marshall Islands"
            // , "Martinique (French)": "Martinique (French)"
            // , "Mauritania": "Mauritania"
            // , "Mauritius": "Mauritius"
            // , "Mayotte": "Mayotte"
            // , "Mexico": "Mexico"
            // , "Micronesia": "Micronesia"
            // , "Moldova": "Moldova"
            // , "Monaco": "Monaco"
            // , "Mongolia": "Mongolia"
            // , "Montenegro": "Montenegro"
            // , "Montserrat": "Montserrat"
            // , "Morocco": "Morocco"
            // , "Mozambique": "Mozambique"
            // , "Myanmar": "Myanmar"
            // , "Namibia": "Namibia"
            // , "Nauru": "Nauru"
            // , "Nepal": "Nepal"
            // , "Netherlands": "Netherlands"
            // , "Netherlands Antilles": "Netherlands Antilles"
            // , "New Caledonia (French)": "New Caledonia (French)"
            // , "New Zealand": "New Zealand"
            // , "Nicaragua": "Nicaragua"
            // , "Niger": "Niger"
            // , "Nigeria": "Nigeria"
            // , "Niue": "Niue"
            // , "Norfolk Island": "Norfolk Island"
            // , "North Korea": "North Korea"
            // , "Northern Mariana Islands": "Northern Mariana Islands"
            // , "Norway": "Norway"
            // , "Oman": "Oman"
            // , "Pakistan": "Pakistan"
            // , "Palau": "Palau"
            // , "Panama": "Panama"
            // , "Papua New Guinea": "Papua New Guinea"
            // , "Paraguay": "Paraguay"
            // , "Peru": "Peru"
            // , "Philippines": "Philippines"
            // , "Pitcairn Island": "Pitcairn Island"
            // , "Poland": "Poland"
            // , "Polynesia (French)": "Polynesia (French)"
            // , "Portugal": "Portugal"
            // , "Puerto Rico": "Puerto Rico"
            // , "Qatar": "Qatar"
            // , "Reunion": "Reunion"
            // , "Romania": "Romania"
            // , "Russia": "Russia"
            // , "Rwanda": "Rwanda"
            // , "Saint Helena": "Saint Helena"
            // , "Saint Kitts and Nevis": "Saint Kitts and Nevis"
            // , "Saint Lucia": "Saint Lucia"
            // , "Saint Pierre and Miquelon": "Saint Pierre and Miquelon"
            // , "Saint Vincent and Grenadines": "Saint Vincent and Grenadines"
            // , "Samoa": "Samoa"
            // , "San Marino": "San Marino"
            // , "Sao Tome and Principe": "Sao Tome and Principe"
            // , "Saudi Arabia": "Saudi Arabia"
            // , "Senegal": "Senegal"
            // , "Serbia": "Serbia"
            // , "Sierra Leone": "Sierra Leone"
            // , "Singapore": "Singapore"
            // , "Sint Maarten": "Sint Maarten"
            // , "Slovakia": "Slovakia"
            // , "Slovenia": "Slovenia"
            // , "Solomon Islands": "Solomon Islands"
            // , "Somalia": "Somalia"
            // , "South Africa": "South Africa"
            // , "South Georgia and South Sandwich Islands": "South Georgia and South Sandwich Islands"
            // , "South Korea": "South Korea"
            // , "South Sudan": "South Sudan"
            // , "Spain": "Spain"
            // , "Sri Lanka": "Sri Lanka"
            // , "Sudan": "Sudan"
            // , "Suriname": "Suriname"
            // , "Svalbard and Jan Mayen Islands": "Svalbard and Jan Mayen Islands"
            // , "Swaziland": "Swaziland"
            // , "Sweden": "Sweden"
            // , "Switzerland": "Switzerland"
            // , "Syria": "Syria"
            // , "Taiwan": "Taiwan"
            // , "Tajikistan": "Tajikistan"
            // , "Tanzania": "Tanzania"
            // , "Thailand": "Thailand"
            // , "Timor-Leste": "Timor-Leste"
            // , "Togo": "Togo"
            // , "Tokelau": "Tokelau"
            // , "Tonga": "Tonga"
            // , "Trinidad and Tobago": "Trinidad and Tobago"
            // , "Tunisia": "Tunisia"
            // , "Turkey": "Turkey"
            // , "Turkmenistan": "Turkmenistan"
            // , "Turks and Caicos Islands": "Turks and Caicos Islands"
            // , "Tuvalu": "Tuvalu"
            // , "Uganda": "Uganda"
            // , "Ukraine": "Ukraine"
            // , "United Arab Emirates": "United Arab Emirates"
            // , "United Kingdom": "United Kingdom"
            // , "United States": "United States"
            // , "Uruguay": "Uruguay"
            // , "Uzbekistan": "Uzbekistan"
            // , "Vanuatu": "Vanuatu"
            // , "Venezuela": "Venezuela"
            // , "Vietnam": "Vietnam"
        }
    }
    , "4": {
        "name": "education_d"
        , "text": "Your education domain"
        , "content": {
            "Agriculture Sciences": "Agriculture Sciences"
            , "Sciences Architecture, Urban and Regional Planning": "Sciences Architecture, Urban and Regional Planning"
            , "Art and Design": "Art and Design"
            , "Business Studies, Management Science": "Business Studies, Management Science"
            , "Education, Teacher Training": "Education, Teacher Training"
            , "Engineering, Technology": "Engineering, Technology"
            , "Geography, Geology": "Geography, Geology"
            , "Humanities": "Humanities"
            , "Languages and Philological Sciences": "Languages and Philological Sciences"
            , "Law": "Law"
            , "Mathematics, Informatics": "Mathematics, Informatics"
            , "Medical Sciences": "Medical Sciences"
            , "Natural Sciences": "Natural Sciences"
            , "Social Sciences": "Social Sciences"
            , "Communication and Information Sciences": "Communication and Information Sciences"
            , "Other Areas of Study": "Other Areas of Study"
        }
    }
    , "5": {
        "name": "education_l"
        , "text": "Your education level"
        , "content": {
            "School": "School"
            , "High school": "High school"
            , "University": "University"
            , "Doctoral studies": "Doctoral studies"
        }
    }
    , "6": {
        "name": "work_d"
        , "text": "Your work domain"
        , "content": {
            "Academic/educator": "Academic/educator"
            , "Artist": "Artist"
            , "Clerical/admin": "Clerical/admin"
            , "College/grad student": "College/grad student"
            , "Customer service": "Customer service"
            , "Doctor/health care": "Doctor/health care"
            , "Executive/managerial": "Executive/managerial"
            , "Farmer": "Farmer"
            , "Homemaker": "Homemaker"
            , "Lawyer": "Lawyer"
            , "Programmer": "Programmer"
            , "Retired": "Retired"
            , "Sales/marketing": "Sales/marketing"
            , "Scientist": "Scientist"
            , "Self-employed": "Self-employed"
            , "Sport professional": "Sport professional"
            , "Technician/engineer": "Technician/engineer"
            , "Tradesman/craftsman": "Tradesman/craftsman"
            , "Unemployed": "Unemployed"
            , "Writer": "Writer"
        }
    }
    , "7": {
        "name": "work_l"
        , "text": "Your work experience"
        , "content": {
            "0": "0-2 years"
            , "1": "2-5 years"
            , "2": "5-10 years"
            , "3": "more than 10 years"
            ,
        }
    }
    , "8": {
        "name": "language_n"
        , "text": "Your native language"
        , "content": {
            "Afrikaans": "Afrikaans"
            , "Albanian": "Albanian"
            , "Arabic": "Arabic"
            , "Armenian": "Armenian"
            , "Awadhi": "Awadhi"
            , "Azerbaijani": "Azerbaijani"
            , "Basque": "Basque"
            , "Belarusian": "Belarusian"
            , "Bengali": "Bengali"
            , "Bhojpuri": "Bhojpuri"
            , "Bosnian": "Bosnian"
            , "Bulgarian": "Bulgarian"
            , "Burmese": "Burmese"
            , "Catalan": "Catalan"
            , "Cebuano": "Cebuano"
            , "Chinese": "Chinese"
            , "Croatian": "Croatian"
            , "Czech": "Czech"
            , "Danish": "Danish"
            , "Dutch": "Dutch"
            , "English": "English"
            , "Esperanto": "Esperanto"
            , "Estonian": "Estonian"
            , "Filipino": "Filipino"
            , "Finnish": "Finnish"
            , "French": "French"
            , "Galician": "Galician"
            , "Georgian": "Georgian"
            , "German": "German"
            , "Greek": "Greek"
            , "Gujarati": "Gujarati"
            , "Haitian": "Haitian"
            , "Hausa": "Hausa"
            , "Hebrew": "Hebrew"
            , "Hindi": "Hindi"
            , "Hmong": "Hmong"
            , "Hungarian": "Hungarian"
            , "Icelandic": "Icelandic"
            , "Indonesian": "Indonesian"
            , "Irish": "Irish"
            , "Italian": "Italian"
            , "Japanese": "Japanese"
            , "Kannada": "Kannada"
            , "Khmer": "Khmer"
            , "Korean": "Korean"
            , "Lao": "Lao"
            , "Latin": "Latin"
            , "Latvian": "Latvian"
            , "Lithuanian": "Lithuanian"
            , "Macedonian": "Macedonian"
            , "Maithili": "Maithili"
            , "Malay": "Malay"
            , "Malayalam": "Malayalam"
            , "Maltese": "Maltese"
            , "Marathi": "Marathi"
            , "Norwegian": "Norwegian"
            , "Oriya": "Oriya"
            , "Panjabi": "Panjabi"
            , "Persian/Farsi": "Persian/Farsi"
            , "Polish": "Polish"
            , "Portuguese": "Portuguese"
            , "Romanian": "Romanian"
            , "Russian": "Russian"
            , "Serbian": "Serbian"
            , "Sindhi": "Sindhi"
            , "Slovak": "Slovak"
            , "Slovenian": "Slovenian"
            , "Spanish": "Spanish"
            , "Sunda": "Sunda"
            , "Swahili": "Swahili"
            , "Swedish": "Swedish"
            , "Tamil": "Tamil"
            , "Telugu": "Telugu"
            , "Thai": "Thai"
            , "Turkish": "Turkish"
            , "Ukrainian": "Ukrainian"
            , "Urdu": "Urdu"
            , "Vietnamese": "Vietnamese"
        }
    }
    , "9": {
        "name": "language_o"
        , "text": "Other spoken language"
        , "content": {
            "Afrikaans": "Afrikaans"
            , "Albanian": "Albanian"
            , "Arabic": "Arabic"
            , "Armenian": "Armenian"
            , "Awadhi": "Awadhi"
            , "Azerbaijani": "Azerbaijani"
            , "Basque": "Basque"
            , "Belarusian": "Belarusian"
            , "Bengali": "Bengali"
            , "Bhojpuri": "Bhojpuri"
            , "Bosnian": "Bosnian"
            , "Bulgarian": "Bulgarian"
            , "Burmese": "Burmese"
            , "Catalan": "Catalan"
            , "Cebuano": "Cebuano"
            , "Chinese": "Chinese"
            , "Croatian": "Croatian"
            , "Czech": "Czech"
            , "Danish": "Danish"
            , "Dutch": "Dutch"
            , "English": "English"
            , "Esperanto": "Esperanto"
            , "Estonian": "Estonian"
            , "Filipino": "Filipino"
            , "Finnish": "Finnish"
            , "French": "French"
            , "Galician": "Galician"
            , "Georgian": "Georgian"
            , "German": "German"
            , "Greek": "Greek"
            , "Gujarati": "Gujarati"
            , "Haitian": "Haitian"
            , "Hausa": "Hausa"
            , "Hebrew": "Hebrew"
            , "Hindi": "Hindi"
            , "Hmong": "Hmong"
            , "Hungarian": "Hungarian"
            , "Icelandic": "Icelandic"
            , "Indonesian": "Indonesian"
            , "Irish": "Irish"
            , "Italian": "Italian"
            , "Japanese": "Japanese"
            , "Kannada": "Kannada"
            , "Khmer": "Khmer"
            , "Korean": "Korean"
            , "Lao": "Lao"
            , "Latin": "Latin"
            , "Latvian": "Latvian"
            , "Lithuanian": "Lithuanian"
            , "Macedonian": "Macedonian"
            , "Maithili": "Maithili"
            , "Malay": "Malay"
            , "Malayalam": "Malayalam"
            , "Maltese": "Maltese"
            , "Marathi": "Marathi"
            , "Norwegian": "Norwegian"
            , "Oriya": "Oriya"
            , "Panjabi": "Panjabi"
            , "Persian/Farsi": "Persian/Farsi"
            , "Polish": "Polish"
            , "Portuguese": "Portuguese"
            , "Romanian": "Romanian"
            , "Russian": "Russian"
            , "Serbian": "Serbian"
            , "Sindhi": "Sindhi"
            , "Slovak": "Slovak"
            , "Slovenian": "Slovenian"
            , "Spanish": "Spanish"
            , "Sunda": "Sunda"
            , "Swahili": "Swahili"
            , "Swedish": "Swedish"
            , "Tamil": "Tamil"
            , "Telugu": "Telugu"
            , "Thai": "Thai"
            , "Turkish": "Turkish"
            , "Ukrainian": "Ukrainian"
            , "Urdu": "Urdu"
            , "Vietnamese": "Vietnamese"
        }
    }
    , "10": {
        "name": "interests"
        , "text": "Your interests (1)"
        , "content": {
            "Arts and Entertainment": "Arts and Entertainment"
            , "Autos and Vehicles": "Autos and Vehicles"
            , "Beauty and Fitness": "Beauty and Fitness"
            , "Books and Literature": "Books and Literature"
            , "Business and Industrial": "Business and Industrial"
            , "Computers and Electronics": "Computers and Electronics"
            , "Finance": "Finance"
            , "Food and Drink": "Food and Drink"
            , "Games": "Games"
            , "Hobbies and Leisure": "Hobbies and Leisure"
            , "Home and Garden": "Home and Garden"
            , "Internet and Telecom": "Internet and Telecom"
            , "Jobs and Education": "Jobs and Education"
            , "Law and Government": "Law and Government"
            , "News": "News"
            , "Online Communities": "Online Communities"
            , "People and Society": "People and Society"
            , "Pets and Animals": "Pets and Animals"
            , "Real Estate": "Real Estate"
            , "Reference": "Reference"
            , "Science": "Science"
            , "Shopping": "Shopping"
            , "Sports": "Sports"
            , "Travel": "Travel"
            , "World Localities": "World Localities"
        }
    }
    , "11": {
        "name": "interests_o"
        , "text": "Your interests (2)"
        , "content": {
            "Arts and Entertainment": "Arts and Entertainment"
            , "Autos and Vehicles": "Autos and Vehicles"
            , "Beauty and Fitness": "Beauty and Fitness"
            , "Books and Literature": "Books and Literature"
            , "Business and Industrial": "Business and Industrial"
            , "Computers and Electronics": "Computers and Electronics"
            , "Finance": "Finance"
            , "Food and Drink": "Food and Drink"
            , "Games": "Games"
            , "Hobbies and Leisure": "Hobbies and Leisure"
            , "Home and Garden": "Home and Garden"
            , "Internet and Telecom": "Internet and Telecom"
            , "Jobs and Education": "Jobs and Education"
            , "Law and Government": "Law and Government"
            , "News": "News"
            , "Online Communities": "Online Communities"
            , "People and Society": "People and Society"
            , "Pets and Animals": "Pets and Animals"
            , "Real Estate": "Real Estate"
            , "Reference": "Reference"
            , "Science": "Science"
            , "Shopping": "Shopping"
            , "Sports": "Sports"
            , "Travel": "Travel"
            , "World Localities": "World Localities"
        }
    }
    , "12": {
        "name": "r_sport"
        , "text": "Rate your knowledge in sports? (1 is bad, 5 is excellent)"
        , "content": {
            "1": "1"
            , "2": "2"
            , "3": "3"
            , "4": "4"
            , "5": "5"
        }
    }
    , "13": {
        "name": "r_technology"
        , "text": "Rate your knowledge in technology?"
        , "content": {
            "1": "1"
            , "2": "2"
            , "3": "3"
            , "4": "4"
            , "5": "5"
        }
    }
    , "14": {
        "name": "r_fashion"
        , "text": "Rate your knowledge in fashion?"
        , "content": {
            "1": "1"
            , "2": "2"
            , "3": "3"
            , "4": "4"
            , "5": "5"
        }
    }
    , "15": {
        "name": "r_natural_s"
        , "text": "Rate your knowledge in natural sciences?"
        , "content": {
            "1": "1"
            , "2": "2"
            , "3": "3"
            , "4": "4"
            , "5": "5"
        }
    }
    , "16": {
        "name": "r_politics"
        , "text": "Rate your knowledge in politics?"
        , "content": {
            "1": "1"
            , "2": "2"
            , "3": "3"
            , "4": "4"
            , "5": "5"
        }
    }
    , "17": {
        "name": "r_social_m"
        , "text": "Rate your knowledge in social media?"
        , "content": {
            "1": "1"
            , "2": "2"
            , "3": "3"
            , "4": "4"
            , "5": "5"
        }
    }
    , "18": {
        "name": "r_humanitarian_w"
        , "text": "Rate your knowledge in humanitarian work?"
        , "content": {
            "1": "1"
            , "2": "2"
            , "3": "3"
            , "4": "4"
            , "5": "5"
        }
    }
    , "19": {
        "name": "full_t"
        , "text": "Are you a full time crowdsourcing contributor?"
        , "content": {
            "yes": "Yes"
            , "no": "No"
        }
    }
}