var task_data = {
    "id": "de",
    "type": "dd_mm",
    "Task_21": {
        "name": "HIT21",
        "id": "Task-21",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/126/dcd3a334a64345948cc1a686d91c05e2.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_25": {
        "name": "HIT25",
        "id": "Task-25",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/139/b0bd03203bd744b2988fde4ff96e4746.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_53": {
        "name": "HIT53",
        "id": "Task-53",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/297/a07181d1ff764b118bb95215afa89ff4.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_2": {
        "name": "HIT2",
        "id": "Task-2",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/24/ca5ca27caca94f9fb0617c226477ae35.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_6": {
        "name": "HIT6",
        "id": "Task-6",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/36/239faf3c69e44268ba411a91afd8ca98.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_1": {
        "name": "HIT1",
        "id": "Task-1",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/23/5f635c0fa59f4270a6953f67dcddcda3.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_5": {
        "name": "HIT5",
        "id": "Task-5",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/35/808d0bf9fe9745fca13ab461f86e0e4e.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_47": {
        "name": "HIT47",
        "id": "Task-47",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/267/706b3c5428aa4de2868416bea983741e.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_67": {
        "name": "HIT67",
        "id": "Task-67",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/382/f17b80f065714fd78fda9a6cb52c0057.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_676": {
        "name": "HIT676",
        "id": "Task-676",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/3361/fc60d904cced497d8629c8e2f285e061.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_2883": {
        "name": "HIT2883",
        "id": "Task-2883",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/14058/4ccde118ab3847249193d71eb70cbe02.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_605": {
        "name": "HIT605",
        "id": "Task-605",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/3065/65632311a51e464ba09d12fee1cd02ab.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_1399": {
        "name": "HIT1399",
        "id": "Task-1399",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/6744/70c5826752444b01a03e33b767387a72.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_852": {
        "name": "HIT852",
        "id": "Task-852",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/4011/389695852bdf480caf69b0516f4901c2.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_2423": {
        "name": "HIT2423",
        "id": "Task-2423",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/11799/d9fcea9da87c44f9b6ca89ab5a69ca5b.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_1891": {
        "name": "HIT1891",
        "id": "Task-1891",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/9132/260b9575049c431b83aa92a862a8b2b8.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_3406": {
        "name": "HIT3406",
        "id": "Task-3406",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/17148/c1bc072052e84fe2994a0d93ebfce493.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_2350": {
        "name": "HIT2350",
        "id": "Task-2350",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/11280/fdf1dff30a5f44a8b115c40eaf3d9bf4.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_1140": {
        "name": "HIT1140",
        "id": "Task-1140",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/5721/ed84efcf11b4495a817e8f72c4697679.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_337": {
        "name": "HIT337",
        "id": "Task-337",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/1576/1d4f489cc4bb4e8d9c99d6b63b3652f6.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_1419": {
        "name": "HIT1419",
        "id": "Task-1419",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/6843/c76ed74d035046dfbb100c5370b9a81b.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_1811": {
        "name": "HIT1811",
        "id": "Task-1811",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/8782/87bb02799e374ab08f3adde509108b8f.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_3588": {
        "name": "HIT3588",
        "id": "Task-3588",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/17991/f58587b1be784736b46d9a43e56cac01.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_3863": {
        "name": "HIT3863",
        "id": "Task-3863",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/19613/8d4e209cef94482dbd9884c9e894c0c7.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_1010": {
        "name": "HIT1010",
        "id": "Task-1010",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/4822/32f7988353a14d8f884e73d790592a2f.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
    "Task_980": {
        "name": "HIT980",
        "id": "Task-980",
        "order": "Look at the image below:",
        "text": "",
        "mm": {"0": "http://s3-eu-west-1.amazonaws.com/we-attributes/dress/4665/5ab26833ca5c438aa6ce8fbb3a08684d.jpg.png"},
        "tt": "",
        "op": {
            op0: {
                "op-text": " What pattern is used on her dress? ",
                "0": " animal ",
                "1": " cartoon ",
                "2": " chevron ",
                "3": " floral ",
                "4": " geometry ",
                "5": " houndstooth ",
                "6": " ikat ",
                "7": " letter_numb ",
                "8": " tribal ",
                "9": " plain ",
                "10": " polka dot ",
                "11": " scales ",
                "12": " skull ",
                "13": " squares ",
                "14": " stars ",
                "15": " stripes ",
                "16": " OTHER "
            }
        },
        "ft": ""
    },
}